name: Deploy to Seenode

on:
  workflow_run:
    workflows: ["Email Service CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy application
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Seenode Deployment
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.SEENODE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"gitCommitSha": "${{ github.event.workflow_run.head_sha }}"}' \
            "https://api.seenode.com/v1/applications/${{ secrets.SEENODE_APPLICATION_ID }}/deployments"
